### ISSUE TITLE
While exporting to daemon the owener of files is hardcoded to pack:pack

### ISSUE THREAD

**Issue by dgodd** [buildpacks/roadmap#12]
The exporter should read PACK_USER_ID and PACK_USER_GID instead (I believe that remote exporter already does)

**Comment by sclevine** [comment]
Note that the env vars should be `PACK_USER_ID` and `PACK_GROUP_ID`.

**Comment by dgodd** [comment]
Closed in favor of https://github.com/buildpack/pack/issues/50
