### ISSUE TITLE
Update `pack run` to include all the arguments that `pack build` takes (except for publish). Also update the docs to reflect this.

### ISSUE THREAD

**Issue by ssisil** [buildpacks/roadmap#23]

**Comment by dgodd** [comment]
@ssisil I can't find any documentation of `pack run` in README.md to change. Was there something I didn't find?

**Comment by dgodd** [comment]
https://github.com/buildpack/pack/commit/ba4f203dad4f62da17cced88d484316abd64808b

**Comment by ssisil** [comment]
@dgodd - I don't think there are any docs for run.

**Comment by ameyer-pivotal** [comment]
@sclevine @ssisil I don't believe the readme was updated to reflect this command. I have an initial draft that was written previously that we could leverage if we think this would be useful in our readme. If so, feel free to create a separate story to track adding it (or reopen this, whichever you prefer).
