### ISSUE TITLE
Ability to set env variables when you run `pack build`

### ISSUE THREAD

**Issue by ssisil** [buildpacks/roadmap#25]
__GIVEN__ I want to set environment variables on pack build
__WHEN__ I have the following environment variable file env.list on my local system 

```
# This is a comment
VAR1=value1
VAR2=value2
VAR3
```
__AND__ I have exported VAR3=value3 in my local environment
__AND__ pass it into `pack build` as `--env-file=env.list` flag
__THEN__ the environment variables will be made available read only in the platform directory at build time such that the platform directory looks like this -

```
$ cd /platform/env
$ ls
VAR1 VAR2 VAR3
$ cat VAR1 VAR2 VAR3
value1value2value3
```

**Notes**
- Add to cli readme
- Example in docker
```
# This is a comment
VAR1=value1
VAR2=value2
VAR3

$ docker run --env-file env.list ubuntu env | grep VAR
VAR1=value1
VAR2=value2
VAR3=value3
```

**Comment by ameyer-pivotal** [comment]
@sclevine @ssisil I don't believe this is documented in the readme, or really anywhere for that matter (the flag is in the CLI help, but it doesn't specify syntax).
