### ISSUE TITLE
derive cache volume name from image tag

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/roadmap#28]
**When** I run `pack build my/image:tag -p /path/to/app`
**Then** pack should create or select a cache volume named`pack-cache-<tag-md5>`, where `<tag-md5>` is the md5 of the string `my/image:tag`

This makes more sense than the current behavior of deriving the cache volume from the app path. Reusing an image tag signifies an intention to rebuild an existing image where reusing the same app  path may not.

**Comment by ekcasey** [comment]
@sclevine @jkutner @nebhale 

Do you think builds for `registry.com:my/image:tag` and `other-registry.com:my/image:tag` should use the same cache?

 What about `registry1.com:my/image:tag` and `registry1.com:my/image:other-tag`?

**Comment by sclevine** [comment]
I think different image identifiers should always result in a separate caches. I think we’ll run into a bunch of issues otherwise (e.g., multiple builds could cause race conditions, and different images with similar names could behave unexpectedly)

**Comment by ekcasey** [comment]
released in `pack` `v0.0.9`
