### ISSUE TITLE
Replace `--verbose` with `--quiet` flag. Make `pack` verbose by default.

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpacks/roadmap#32]

**Comment by sclevine** [comment]
Seems like `-q` is suppressing build output from the buildpack. Was this intentional? What's the intended use case for `-q`?

**Comment by ameyer-pivotal** [comment]
@sclevine Yes, it was intended that buildpack output and lifecycle output are both considered verbose and will be quieted

**Comment by ameyer-pivotal** [comment]
Though we can certainly change that easily if we want one or the other to always show.

**Comment by ekcasey** [comment]
@sclevine what output do you think is appropriate for quiet mode?

**Comment by sclevine** [comment]
I think we should at least display the buildpack output. It contains important information, even if the build succeeds.

**Comment by ekcasey** [comment]
released in `pack` `v0.0.9`
