### ISSUE TITLE
Bug: Reused launch layers with updated metadata do not save the updated metadata to the image

### ISSUE THREAD

**Issue by sclevine** [buildpacks/roadmap#34]
**To Reproduce**
- Create buildpack that writes an empty layer
- Change metadata every time
- Observe that metadata stops changing after first build

**Comment by ekcasey** [comment]
reopening until we release new lifecycle images with this fix

**Comment by mgibson1121** [comment]
@sclevine Accepted this ticket with @ekcasey, moving to 0.1.0 release
