### ISSUE TITLE
As a pack CLI user, I must select a builder with: pack set-default-builder

### ISSUE THREAD

**Issue by sclevine** [buildpacks/roadmap#36]
**Acceptance Criteria**
**When** I install the `pack` CLI on a workstation that has not had v0.1.0 installed at any point
**And** `pack set-default-builder` has not been run with pack v0.1.0
**And** I run `pack build` or `pack run`
**Then** I see:
```
Please select a default builder with:

pack set-default-builder [builder image]

Suggested builders:
  Cloud Foundry:  cloudfoundry/cnb
  Heroku:         heroku/buildpacks

Sample builders:
  Samples:        packs/samples
```
Notes:
- suggestions are ordered randomly (except for Samples, which stays at the bottom)
- After set-default-builder, do not show this message
- May have to record the pack CLI version in the config file

**Comment by ameyer-pivotal** [comment]
To solution a tad, I think one way we could address this is to leave the initial default builder `""`, rather than populating it on first config load like we currently do. Then we can use `""` to key off of for determining whether they need to select a default builder.

**Comment by sclevine** [comment]
TODO: add more detail for each image (e.g., bionic vs. cflinuxfs3, buildpacks included), also recommend `pack inspect-builder`

**Comment by ekcasey** [comment]
This feature is essentially done in master of pack. However, I temporarily commented out the actual references to the suggested builders b/c neither currently work with master of pack

We should probably hold on acceptance until the builders work...

**Comment by mgibson1121** [comment]
Per speaking with @djoyahoy, holding off testing this until the CF/heroku suggestions are truly randomized.

**Comment by ekcasey** [comment]
After discussion with @sclevine @nebhale @jkutner @hone It seems that we would like to take "Samples Builders", section out of the suggestions.

This raises an interesting question... our acceptance tests run against the samples builder, once the samples builder is no longer a default or even a suggested builder this doesn't seem as appropriate any more. What should we do instead?

Is testing against a builder created with `pack create-builder` sufficient? Should we also test that our suggested builders work? I think that would be probably be good for our users.

**Comment by mgibson1121** [comment]
@ekcasey Is this story ready for acceptance?  I recall during standup @sclevine mentioning a slightly more complex UX around randomly generating the order of the builders, but also grouping the CF builders together.

**Comment by mgibson1121** [comment]
@ekcasey @ameyer-pivotal @djoyahoy Any pointers for how to mimic this scenario on my machine?  ```When I install the pack CLI on a workstation that has not had v0.1.0 installed at any point```

**Comment by djoyahoy** [comment]
@mgibson1121 you can delete the `~/.pack` directory (`rm -r ~/.pack`) if it exists.

**Comment by mgibson1121** [comment]
This passes acceptance
