### ISSUE TITLE
Use non-red (or red-like) hues for all non-error output.

### ISSUE THREAD

**Issue by sclevine** [buildpacks/roadmap#40]
These hues should only be used to draw attention to errors.

**Acceptance Criteria**
**When** I execute any `pack` subcommand
**Then** I only see red or red-like hues for error output

**Comment by mgibson1121** [comment]
**When** I execute a command successfully using the pack CLI (an error does not occur)
**Then** I see green non error output text styled in green

**Notes**

- Green won the styling survey based on seven responses.  I also think green looks the best and leaves the least room for ambiguity.  

- It is my understanding that tip text is styled in green.  We should monitor if this turns into a UX problem in the future.  If it does, I would recommend changing the tip text to yellow

- The color can be modified by going into pack/style/style.go and changing `var Key = color.MagentaString`to `var Key = color.GreenString`

**Comment by ekcasey** [comment]
delivered in pack-0.1.0-build.70-darwin

**Comment by mgibson1121** [comment]
@ekcasey @ameyer-pivotal Tested this out in pack-0.1.0-build.70-darwin.  Output is green.  Per my discussion with @ameyer-pivotal Wednesday morning, he felt pretty strongly that the output color should be a normal shade that is bolded.  Although green won the survey, I differ to him.  @ameyer-pivotal do you want me to reject and rewrite the ticket?
