### ISSUE TITLE
When pulling images using the pack CLI, we should pass Docker's progress bar through. (Docker will actually send the progress bar visualization over the logs API.)

### ISSUE THREAD

**Issue by sclevine** [buildpacks/roadmap#41]
**Acceptance Criteria**
**When** Any images are pulled from a registry using the docker daemon
**Then** I see the standard docker loading bar, streamed from daemon

**Notes**
- CF Local has example code for this

**Comment by mgibson1121** [comment]
Tested with @joaopapereira This passes acceptance
