### ISSUE TITLE
`packs/samples:v3alpha2` currently reference `packs/run:0.0.1-rc.528` instead of `packs/run:v3alpha2`

### ISSUE THREAD

**Issue by sclevine** [buildpacks/roadmap#43]
The `packs/samples:v3alpha2`
The run image should be dynamically chosen during `pack build` so that patched OS packages are always used.

**Acceptance Criteria**
**When** I build an OCI image using:
```
pack build my-image
```
**Then** I observe that `packs/run:v3alpha2` is recorded in the image metadata
**And** I observe that the base image layers in `my-image` correspond to the layer in `packs/run:v3alpha2` at the time `pack build` was executed

**Comment by mgibson1121** [comment]
Tested with Joao, this passes acceptance.
