### ISSUE TITLE
As a pack user, I only see a single copy of the generated image SHAs

### ISSUE THREAD

**Issue by sclevine** [buildpacks/roadmap#45]
Remove "wall of SHAs" coming from ggcr (but keep exporter SHAs).

**Acceptance Criteria**
**When** I build an OCI image with `pack build` and any combination of valid options
**Then** I don't see any SHAs that originate from the go-containerregistry
**And** I see the SHAs intentionally output by the exporter

**Comment by mgibson1121** [comment]
Not seeing SHAs generated from go-containerregistry when I run pack build, accepting.
