### ISSUE TITLE
As a pack or lifecycle user, I do not observe timestamps on lifecycle log output

### ISSUE THREAD

**Issue by sclevine** [buildpacks/roadmap#46]
**Acceptance Criteria**
**When** I build an OCI image using `pack build my-image` (with out without the `--publish` flag)
**Then** I don't observe any timestamps on output that is generated the lifecycle's implementation code.

**Notes**
- These timestamps come from `log` package lines in the lifecycle. The Go `log` stdlib package can be adjusted globally to remove these lines. This may be necessary for ggcr lines.

**Comment by mgibson1121** [comment]
Accepting this story -- don't see any timestamp in the lifecycle output when I pack build the node app in pack/acceptance/testdata/node_app
